### ISSUE TITLE
Not compatible with DFhack 0.4704-r2?

### ISSUE THREAD

**Issue by YuweiAstro** [mifki/df-twbt#101]
Hi,
I'm using the latest version of TWBT(6.6.1) and DFHack (dfhack-0.47.04-r2-OSX-64bit-gcc-7.5.0) on OSX 10.15.6. And the game version is 0.47.4.
I've copied the files according to the TWBT Setup [here](https://www.reddit.com/r/dwarffortress/comments/9uzz3w/guide_to_manually_updating_lazy_mac_pack_osx/)
And when I run the game from pyLNP, the terminal reports:
```
$ /Applications/Lazy\ Mac\ Pack\ v0.47.04\ dfhack-b1/df_osx/dfhack ; exit;
dfhack: attempting to hook in
Loading bindings from data/init/interface.txt
Resetting textures
Plugin twbt was not built for this version of DFHack.
Plugin: 0.44.12-r2, DFHack: 0.47.04-r2
DFHack is ready. Have a nice day!
DFHack version 0.47.04-r2 (release) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]# 
```
And the text in the game are gibberish.
I wonder how to fix it.
Thanks :)

**Comment by YuweiAstro** [comment]
The gibberish characters seems to be only of some graphic mods, whereas most of them have issue displaying punctuation.
I'm using Mayday and it looks just like the [screenshot](http://www.bay12forums.com/smf/index.php?topic=138754.0) on the left.

**Comment by txtsd** [comment]
Get the latest versions here for now:
https://github.com/thurin/df-twbt/releases

**Comment by YuweiAstro** [comment]
> Get the latest versions here for now:
> https://github.com/thurin/df-twbt/releases

It worked. Thanks!
