### ISSUE TITLE
Can see through floor

### ISSUE THREAD

**Issue by vanatteveldt** [mifki/df-twbt#33]
I freshly installed df, dfhack, and twbt today, using obsidian graphics font and regular ascii text font. 

I dug a shallow room just after embarking starting from a down stairs. It is a haunted biome, and it is raining something nasty. Without multilevel it looks like this:

Ground level:
![l0](https://cloud.githubusercontent.com/assets/1736240/10521217/dde9678a-736e-11e5-9d73-47a6eba973aa.png)

Room at z-1:
![l2](https://cloud.githubusercontent.com/assets/1736240/10521215/ddd18de0-736e-11e5-946e-66174752ae94.png)

With multilevel, I can see through the floor, so the livestock and manager that are downstairs appear as if they are on the surface (but slightly shadowed):

![multilevel](https://cloud.githubusercontent.com/assets/1736240/10521216/ddd27278-736e-11e5-8df1-2f46575f5c5c.png)

Edit: Interestingly, it only seems to be some tiles, and the pattern changes all the time. It is raining some kind of dizzying muck (the biome is haunted, I think), so maybe that's triggering the problem?

I tried playing a bit with fogdensity but it doesn't really seem to do anything. Did I configure something wrong?

**Comment by pronvit** [comment]
What is your OS?

**Comment by vanatteveldt** [comment]
Linux (Ubuntu; with i3 window manager if that matters)

**Comment by fricy** [comment]
Actually this is a duplicate report for #18. Thx for the screenshots, I never realized you can see through the floor. Cool. :)   
I've already [patched Obsidian](https://github.com/fricy/Obsidian/commit/adfdeaeee01c82cb02597809d2b0410a602c5e3f) as a workaround for this bug, get it [here.](https://github.com/fricy/Obsidian/archive/40.24.zip)

**Comment by vanatteveldt** [comment]
Heh, I could not have guessed that from the bug descriptions :). But I seem to recall that obsidian does something weird with grass tiles, so in a way I guess it is no surprise. Thanks for the patch!
