### ISSUE TITLE
Zoom offset errors

### ISSUE THREAD

**Issue by indivisible** [mifki/df-twbt#38]
Zooming causes the mouse indicator and construction suspended markers to display at incorrect positions on 42.05 Linux (with latest devel dfhack). See http://i.imgur.com/hPAKf9u.png

**Comment by pronvit** [comment]
Probably you didn't install the three plugins bundled with twbt, specifically `resume` in this case.

**Comment by indivisible** [comment]
Thanks, you're right. Please close the bug and add an INSTALL file :P
