### ISSUE TITLE
Adventure Mode Build Blackout

### ISSUE THREAD

**Issue by ArrowThunder** [mifki/df-twbt#56]
Going to the (b)uild screen in Adventure mode in 0.43.03 with TWBT creates a black screen. The menu options show, but TWBT overrides the other tiles, making it impossible to build!

If it's any help, the problem does not seem to happen in TWBT legacy.

**Comment by pronvit** [comment]
Which TWBT version is that? This should be fixed in v5.78 https://github.com/mifki/df-twbt/releases/tag/v5.78

**Comment by ArrowThunder** [comment]
That was 5.70. I use the LNP, and just went through the long and ardous process of upgrading so I could confirm, but yes, it does seem to be fixed in 5.78. Multi-layered view is a little wonky when it comes to the build interface, because it seems to prioritize other build commands over physical entities when viewing things from above, but it does seem to work. Thanks!

**Comment by pronvit** [comment]
Hey, can you share a save in which I can test building? I do not play adventure mode so I don't even know how to get to a stage when I can build.

**Comment by lethosor** [comment]
You should be able to test it in any save by pressing "b".

**Comment by pronvit** [comment]
@lethosor In what "any save"? If I just start an adv mode game and press b, I get "You cannot build here".

**Comment by lethosor** [comment]
Oh, are you in an existing site? You might have to move to an unsettled area (e.g. fast travel a short distance outside of the town).

**Comment by pronvit** [comment]
Ah, just that, cool, thanks.
