### ISSUE TITLE
Problems loading graphics for workshops

### ISSUE THREAD

**Issue by aikoncwd** [mifki/df-twbt#68]
I don't know why, but the **Phoebus/SpaceFox** is showing some workshops different in the actual version (LNP 0.44.02-r4), this is how *still* looks:

![ugly](https://imgur.com/Zjhp3pT.png)

On the last version (LNP 0.43.05-r11), the *still* workshop looks like this:

![nice](https://imgur.com/EmjZQPw.png)

The tileset is the same, so I think the problem is with twbt plugin ¿?

**Comment by carterscottm** [comment]
Can confirm. Other tiles are also shown incorrectly, such as coffins, slabs, and planted farm plots.

**Comment by pronvit** [comment]
Replied in DFgraphics repo issue.
