### ISSUE TITLE
Is there going to be an update for 47_03

### ISSUE THREAD

**Issue by LordBSD** [mifki/df-twbt#96]
Thanks.

**Comment by UnseenBook** [comment]
I'm sure there will be an update, there are already Pull requests for the new versions.
If you really want you can try and compile that version. If you play on Linux i can even provide you a build.

**Comment by LordBSD** [comment]
That should work and I would be grateful for one I am on gentoo linux. I am using dwarf fortress 43_03, and dfhack v0.43.03.Thanks.

**Comment by lethosor** [comment]
0.47.03?

**Comment by LordBSD** [comment]
Yes my mistake I am sorry. I am trying to get the latest version working for myself. Just to be clear I have dwarf fortress 0.47.03 and DFHack version 0.47.03-alpha0 (development build 0.47.03-alpha0-19-g53da38ca) on x86_64 (GIT) working. So now I was just hoping to get twbt as its the last thing i need and a great plugin. Thanks.

**Comment by LordBSD** [comment]
I have three boxes that I try to run current versions of df, dfhack and df-twbt on. One is win 10 64 (current builld)  one is arch linux and one is gentoo. Ill help you in any way I can let me know. I have it mostly working on FreeBSD too. Well not dfhack or twbt but soundsense, dwarf therapist and dwarf fortress itself of course.

**Comment by UnseenBook** [comment]
Here is the TWBT plugin. Note that you still need to "install" the files in the dist folder of this repo. (.png files in data/art/ and realcolors.lua file in hack/lua/)
Build on Arch Linux, but should work on Gentoo. I build it from [PR 95](https://github.com/mifki/df-twbt/pull/95)

[twbt_plugin.zip](https://github.com/mifki/df-twbt/files/4258222/twbt_plugin.zip)

**Comment by LordBSD** [comment]
Thank you UnseenBook! Thank you all.

mike@core ~/dwarf $ ./dfhack
Loading bindings from data/init/interface.txt
Resetting textures
Warning: Plugin twbt compiled for DFHack 0.47.03-alpha0-35-g92eb8b05, running DFHack 0.47.03-alpha0-19-g53da38ca
TWBT: version 5.xx
TWBT: no display patch (not an error)
DFHack is ready. Have a nice day!
DFHack version 0.47.03-alpha0 (development build 0.47.03-alpha0-19-g53da38ca) on x86_64
Type in '?' or 'help' for general help, 'ls' to see all commands.
[DFHack]#

**Comment by LordBSD** [comment]
Any chance I can get this plugin built again but for DFHack 0.47.04-alpha0. Even better I can build it myself, I just dont know how to change the version so it works correctly and compiles. I have no problem editing src and compiling, but if I could just be led in the right direction it would be great. Im gonna poke around too while I wait. Trying to upgrade today. Thanks.

**Comment by LordBSD** [comment]
Any chance I can get this plugin built again but for DFHack 0.47.04-alpha0. Even better I can build it myself, I just dont know how to change the version so it works correctly and compiles. I have no problem editing src and compiling, but if I could just be led in the right direction it would be great. Im gonna poke around too while I wait. Trying to upgrade today. Thanks.

**Comment by nshcat** [comment]
https://github.com/thurin/df-twbt/commit/1e94a0dfdb4f5947e9fd3da14a83cfbe65c26f08

**Comment by LordBSD** [comment]
Thanks nshcat
